services:
  wg-easy:
    environment:
      # Change this to your host's public ip address or dns
      - WG_HOST= 
      # Web UI Password:
      - PASSWORD=
      - WG_PORT=51820
      # Wireguard private CIDR and DNS
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=1.1.1.1, 8.8.8.8
      # Use if restrict access to wireguard server
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
    network_mode: bridge
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
